pipeline {
    agent any

    environment {
        PYTHON = 'python'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/junelus/E-Commerce-Platform-QA-Automation.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat "'C:\\Users\\big_j\\AppData\\Local\\Programs\\Python\\Python312\\python.exe' -m pip install --upgrade pip"
                bat "'C:\\Users\\big_j\\AppData\\Local\\Programs\\Python\\Python312\\python.exe' -m pip install -r requirements.txt"
            }
        }

        stage('Run Selenium Tests') {
            steps {
                // Running the login test
                bat "'C:\\Users\\big_j\\AppData\\Local\\Programs\\Python\\Python312\\python.exe' selenium_tests/login_test.py"

                // Running the product search test
                bat "'C:\\Users\\big_j\\AppData\\Local\\Programs\\Python\\Python312\\python.exe' selenium_tests/product_search_test.py"

                // Running the purchase flow test
                bat "'C:\\Users\\big_j\\AppData\\Local\\Programs\\Python\\Python312\\python.exe' selenium_tests/purchase_flow_test.py"
            }
        }

        stage('Publish Test Results') {
            steps {
                // Here you could configure test reports, logs, etc.
                echo "All tests have been executed!"
            }
        }
    }

    post {
        always {
            // Archive any test results or screenshots
            archiveArtifacts artifacts: '**/selenium_tests/screenshots/*.png', allowEmptyArchive: true
        }
    }
}
